name: Deploy to ProFreeHost FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ezyro_41258630 }}
        username: ${{ secrets.ezyro_41258630 }}
        password: ${{ secrets.89408940 }}
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
